# Generated by Django 4.1.1 on 2023-02-20 13:33

import API.Misi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Misi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=120)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=API.Misi.models.uploadTo)),
                ('poin', models.IntegerField()),
                ('waktu', models.IntegerField()),
                ('status', models.CharField(max_length=24)),
            ],
        ),
    ]
