# Generated by Django 4.1.1 on 2023-02-22 01:53

import API.Misi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Misi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=120)),
                ('gambar', models.ImageField(blank=True, null=True)),
                ('poin', models.IntegerField()),
                ('waktu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TerimaMisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_misi', models.IntegerField()),
                ('misi', models.CharField(max_length=120)),
                ('id_user', models.IntegerField()),
                ('user', models.CharField(max_length=150)),
                ('waktu', models.IntegerField()),
                ('poin', models.IntegerField()),
                ('status', models.CharField(max_length=24)),
            ],
        ),
    ]
